### ISSUE TITLE
feature: add leaderboard

### ISSUE THREAD

**Issue by richard-ramos** [status-im/meritocracy#14]

**Comment by ceripower** [comment]
Specs:

-  Leaderboard - Place to check the usage of the app and seeing how kudos are being allocated (received, allocated, and forfeited balances)
-  A way to gather all the praise comments for everyone and aggregate them into one place (like a kudos wall)

**Comment by ceripower** [comment]
Hey @richard-ramos - is the leaderboard now visible to all participants, and can we consider this one as closed?

**Comment by richard-ramos** [comment]
Yup!
