### ISSUE TITLE
Alphabetise `Contributor List`

### ISSUE THREAD

**Issue by ceripower** [status-im/meritocracy#17]
In the `Choose Contributor` dropdown on the DApp Home tab, the list of names is alphabetised in what looks like `ABCDEFabcdef` order, meaning that names not capitalised appear at the bottom of the list. It's a minor thing that would make searchability a little easier, though not critical (you can still type the name you're looking for and find it that way, versus scrolling through the list of names)

**Comment by richard-ramos** [comment]
Fixed!
