### ISSUE TITLE
Increase amounts of SNT allocated

### ISSUE THREAD

**Issue by ceripower** [status-im/meritocracy#19]
Schedule for gradually increasing the supply of SNT being allocated. Suggestion for amounts per participant, per week:

- Early April - 5 SNT 
- Mid April - 10 SNT 
- May - 100 SNT (~$2.2) | Total cost $104 p/w
- June - 500 SNT (~$11.3) | Total cost $521 p/w
- July onwards - review again once contract audited and make a decision on target future allocation amount.

Number of participants: 46

Wdyt @jonathanbarker @danbigm?

**Comment by jonathanbarker** [comment]
@ceripower This looks great to me. I think the final amount is good balance of enough balance of a significant amount over the course of the year, whilst not being so large to encourage bad behaviours .

**Comment by jonathanbarker** [comment]
Also - I updated the POps budget to include the cost.

**Comment by DanBigM** [comment]
Looks good to me!
From the swarm leadership call today one takeway was that it is not all about financial incentives. Maybe the gesture with the total of 100 SNTp/w will be enough? Let's revisit that in a month and decide then after getting some quick feedback.
Would we fix the amount of SNT to the fiat value to a certain extent? If suddenly the price increases, do we allow a correction? (probably that would come with an overall improvement of our situation, but just trying to think of all possibilities)

**Comment by ceripower** [comment]
> From the swarm leadership call today one takeway was that it is not all about financial incentives. Maybe the gesture with the total of 100 SNTp/w will be enough?

Totally - I think as long as the amount of money is immaterial, the SNT involved are more symbolic rather than turning this into some extrinsically motivated exercise. I do think it's important to increase the value being distributed over time as a primer to get people comfortable for where Status is heading (i.e. meritocratic, more democracy in funding).

> Would we fix the amount of SNT to the fiat value to a certain extent?

I would say yes - we should keep an eye on the value of SNT to make sure that the amount we're allocating doesn't rise above that 'immaterial' threshold before we're ready for it to do that.

**Comment by ceripower** [comment]
Tracking payments made/cost [here](https://docs.google.com/spreadsheets/d/1KN5an52_kzFGVV_rK9EQtTBHFE-x0TlD1wi6gnLnY5o/edit#gid=0)

**Comment by DanBigM** [comment]
thanks, @ceripower ! I set the limit to reconsider the amount at USD/SNT 0.1

**Comment by ceripower** [comment]
@richard-ramos Do we have the option to have two groups of participants, e.g. one group (core contributors/ambassadors) and another (community contributors)? Just thinking that sign up (and the ability to send/receive kudos) currently is open, but in future if we get more sign ups, it might make sense to make newer community contributors `recipient-only` while we re-calibrate the budget and figure out what we can afford to fund.

**Comment by richard-ramos** [comment]
Sounds like a great idea! 
current version does not support that, but we could add that in the Roadmap for the next version of the meritocracy dapp.

**Comment by jarradh** [comment]
➤ ceri power commented:

Confirming here that we're on SNT 100 p/w for the remainder of May, tentative plan to increase to SNT 500 p/w in June

**Comment by 0xc1c4da** [comment]
➤ Ceri Power commented:

Closing this issue - SNT 500 seems to work fine as a low risk amount. I don't foresee the contract being audited in the near future so I don't think it makes sense to increase the weekly allocated amount.
