### ISSUE TITLE
Hamburger/menu button has no action

### ISSUE THREAD

**Issue by jonathanbarker** [status-im/meritocracy#22]
Love the new UI of the Meritocracy app. 

Issue: 
When I click the hamburger menu icon that appears in the top right (next to "Status Meritocracy") nothing happens. The icon highlights but the expected behaviour (a drop down menu of sorts?) does not appear. 

Not sure if this is a bug, or if still a feature under development.

**Comment by ceripower** [comment]
> Not sure if this is a bug, or if still a feature under development.

Bug :D thanks for reporting

**Comment by richard-ramos** [comment]
Fixed!
