### ISSUE TITLE
Own posts are displayed as from wallet address rather than display name

### ISSUE THREAD

**Issue by ceripower** [status-im/meritocracy#28]
When looking at the wall, everyone else's posts (kudos) are displayed with the username as the identifier. With my own posts, I am shown as a wallet address (rather than user name). Not sure if this is unique to me as I'm an admin, or maybe it's something others are seeing when looking at their own posts.

![IMG_1742](https://user-images.githubusercontent.com/25318254/57295804-34e70600-70c3-11e9-854a-d7175bdf53af.PNG)

**Comment by richard-ramos** [comment]
Fixed with #29
