### ISSUE TITLE
Lalo not showing in the leaderboard

### ISSUE THREAD

**Issue by ceripower** [status-im/meritocracy#36]
I added Lalo to the registry as a contributor, but can't see him in the leaderboard.

I notice that his transactions are showing, except displaying his address, rather than his display name.

His address: 0xE86eF0955Bdd2A4865F16f5b3df7d0eC8d3a4050

![IMG_3129](https://user-images.githubusercontent.com/25318254/60576835-107f7100-9d76-11e9-8507-ebfbd9dcdc63.PNG)
![IMG_3130](https://user-images.githubusercontent.com/25318254/60576840-12e1cb00-9d76-11e9-9354-6788cb8eb181.PNG)

**Comment by richard-ramos** [comment]
This has been fixed.
